import path from "node:path";
import fs from "fs-extra";

export async function writePdfReport(runPath: string, data: {
  project: string;
  branch: string;
  timestamp: string;
  ecosystemSummary: string[];
  findings: Array<{ id: string; severity: string; title: string; file: string }>;
  coverage?: number; // 0-1 fraction optional
}) {
  const reportPath = path.join(runPath, "report.pdf");
  
  // Mock PDF generation - in real implementation, this would use a PDF library
  const reportContent = `
# Uatu Audit Report

**Project:** ${data.project}  
**Branch:** ${data.branch}  
**Timestamp:** ${data.timestamp}  
**Ecosystems:** ${data.ecosystemSummary.join(", ")}  
${typeof data.coverage === 'number' ? `**Coverage (est.):** ${(data.coverage*100).toFixed(0)}%  ` : ""}

## Findings Summary

Total Findings: ${data.findings.length}

### By Severity:
- High: ${data.findings.filter(f => f.severity === "high").length}
- Medium: ${data.findings.filter(f => f.severity === "medium").length}
- Low: ${data.findings.filter(f => f.severity === "low").length}

## Detailed Findings

${data.findings.map(f => `### ${f.id}: ${f.title}
- **Severity:** ${f.severity}
- **File:** ${f.file}
`).join("\n")}

---
Generated by Uatu Audit Tool
  `.trim();
  
  await fs.writeFile(reportPath, reportContent);
  return reportPath;
}
