/**
 * Testing Step Executors
 *
 * Steps that generate and run test cases for audit findings.
 */

import * as path from 'path';
import * as fs from 'fs-extra';
import type {
  StepDefinition,
  StepContext,
  StepResult,
  DeterministicStepConfig,
} from '../../definitions/types';
import { logger } from '../../../utils/logger';
import {
  generateTestForFinding,
  detectTestFramework,
  type AuditFinding,
  type GeneratedTest,
} from '../../../services/testCaseGenerator.js';
import { publishAuditResults } from '../../../services/auditResultsPublisher.js';
import { getDb } from '../../../db/index.js';
import { auditJobs } from '../../../db/schema.js';
import { eq } from 'drizzle-orm';

const log = logger.child({ module: 'testing-steps' });

// ============================================================================
// Main Executor
// ============================================================================

/**
 * Execute a testing step
 */
export async function executeTestingStep(
  step: StepDefinition,
  config: DeterministicStepConfig,
  context: StepContext
): Promise<StepResult> {
  const executor = TESTING_EXECUTORS[config.function];

  if (!executor) {
    return {
      success: false,
      error: `Unknown testing function: ${config.function}`,
      findings: [],
    };
  }

  return executor(step, config, context);
}

// ============================================================================
// Step Executor Type
// ============================================================================

type TestingExecutor = (
  step: StepDefinition,
  config: DeterministicStepConfig,
  context: StepContext
) => Promise<StepResult>;

// ============================================================================
// Generate Tests Step
// ============================================================================

/**
 * Generate test cases for audit findings
 * Only generates tests for high/critical severity findings
 */
const generateTests: TestingExecutor = async (step, config, context) => {
  const { projectPath, job } = context;
  const jobId = job.id;

  log.info('Generating test cases for findings', { jobId });

  await context.onProgress?.(5, 'Loading audit findings...');

  // Get job metadata to find workspace info
  const db = getDb();
  const [jobRecord] = await db
    .select()
    .from(auditJobs)
    .where(eq(auditJobs.id, jobId))
    .limit(1);

  if (!jobRecord || !jobRecord.metadata) {
    return {
      success: false,
      error: 'Job metadata not found',
      findings: [],
    };
  }

  const workspace = (jobRecord.metadata as any).workspace;
  if (!workspace) {
    return {
      success: false,
      error: 'Workspace info not found in job metadata',
      findings: [],
    };
  }

  const sourcePath = workspace.sourcePath;
  const testsPath = workspace.testsPath;

  // Ensure tests directory exists
  await fs.ensureDir(testsPath);

  // Create .gitignore in tests directory to prevent git pollution
  const gitignorePath = path.join(testsPath, '.gitignore');
  const gitignoreContent = `# Auto-generated by UatuAudit - DO NOT COMMIT THESE FILES
# These test files are generated during audits and should not be version controlled

# Ignore all generated test files
*.t.sol
*.test.ts
*.test.js

# But keep this .gitignore
!.gitignore

# Keep any manually written tests (if needed)
# If you want to keep certain tests, add them here with !filename.t.sol
`;

  await fs.writeFile(gitignorePath, gitignoreContent, 'utf-8');
  log.info('Created .gitignore in tests directory', { testsPath });

  await context.onProgress?.(10, 'Loading findings...');

  // Get all findings from audit_results.findings JSONB
  const { auditResults } = await import('../../../db/schema.js');
  const [results] = await db
    .select()
    .from(auditResults)
    .where(eq(auditResults.jobId, jobId));

  if (!results || !results.findings) {
    await context.onProgress?.(100, 'No findings to test');
    return { success: true, findings: [] };
  }

  const findingsData = results.findings as any[];

  // Convert to AuditFinding format
  const allFindings: AuditFinding[] = findingsData.map((f: any) => ({
    id: f.id || f.findingId,
    findingId: f.findingId || f.id,
    title: f.title || 'Untitled Finding',
    description: f.description || '',
    recommendation: f.recommendation || undefined,
    severity: f.severity || 'info',
    filePath: f.location?.file || undefined,
    lineStart: f.location?.line || undefined,
    lineEnd: f.location?.lineEnd || undefined,
    functionName: f.location?.function || undefined,
    contractName: f.location?.contract || undefined,
    tool: f.tool || undefined,
  }));

  // Get audit depth from job
  const auditDepth = job.auditDepth || 'standard';

  // Filter findings based on audit depth
  let testableFindings: AuditFinding[];

  if (auditDepth === 'deep') {
    // DEEP MODE: Test ALL severity levels (critical, high, medium, low, info)
    // Generate comprehensive test coverage for maximum security validation
    testableFindings = allFindings.filter(
      (f) => ['critical', 'high', 'medium', 'low', 'info'].includes(f.severity)
    );
    log.info('🔬 DEEP MODE: Generating comprehensive test suite for ALL findings', {
      total: allFindings.length,
      testable: testableFindings.length,
      critical: testableFindings.filter(f => f.severity === 'critical').length,
      high: testableFindings.filter(f => f.severity === 'high').length,
      medium: testableFindings.filter(f => f.severity === 'medium').length,
      low: testableFindings.filter(f => f.severity === 'low').length,
      info: testableFindings.filter(f => f.severity === 'info').length,
    });
  } else {
    // STANDARD MODE: Test only critical and high severity findings
    testableFindings = allFindings.filter(
      (f) => f.severity === 'critical' || f.severity === 'high'
    );
    log.info('⚡ STANDARD MODE: Generating tests for critical/high severity findings', {
      total: allFindings.length,
      testable: testableFindings.length,
      critical: testableFindings.filter(f => f.severity === 'critical').length,
      high: testableFindings.filter(f => f.severity === 'high').length,
    });
  }

  log.info('Found testable findings', {
    depth: auditDepth,
    total: allFindings.length,
    testable: testableFindings.length,
  });

  if (testableFindings.length === 0) {
    return {
      success: true,
      output: {
        testsGenerated: 0,
        message: 'No high/critical findings to generate tests for',
      },
      findings: [],
    };
  }

  await context.onProgress?.(20, `Generating tests for ${testableFindings.length} findings...`);

  // Detect test framework
  const framework = await detectTestFramework(sourcePath);
  log.info('Detected test framework', { framework });

  const generatedTests: GeneratedTest[] = [];
  const errors: Array<{ findingId: string; error: string }> = [];

  // Determine test generation strategy based on audit depth
  const generateMultipleVariants = auditDepth === 'deep';
  const testVariants: Array<'basic' | 'edge-case' | 'fuzz'> = generateMultipleVariants
    ? ['basic', 'edge-case', 'fuzz'] // Deep mode: 3 variants per finding
    : ['basic']; // Standard mode: 1 test per finding

  const totalTests = testableFindings.length * testVariants.length;
  let testsProcessed = 0;

  log.info('Test generation strategy', {
    depth: auditDepth,
    findingsToTest: testableFindings.length,
    variantsPerFinding: testVariants.length,
    totalTestsToGenerate: totalTests,
  });

  // Generate tests for each finding
  for (let i = 0; i < testableFindings.length; i++) {
    const finding = testableFindings[i];

    // In deep mode, generate multiple test variants per finding
    for (const variant of testVariants) {
      testsProcessed++;
      const progress = 20 + (testsProcessed / totalTests) * 70;

      const variantLabel = variant === 'basic' ? '' : ` [${variant}]`;
      await context.onProgress?.(
        progress,
        `Generating test ${testsProcessed}/${totalTests}: ${finding.title.substring(0, 40)}${variantLabel}...`
      );

      try {
        log.info('Generating test for finding', {
          findingId: finding.findingId,
          title: finding.title,
          severity: finding.severity,
          variant,
          depth: auditDepth,
        });

        const test = await generateTestForFinding(finding, sourcePath, framework);

        // Modify test code based on variant in deep mode
        let finalTestCode = test.testCode;
        let finalFileName = test.testFileName;

        if (generateMultipleVariants && variant !== 'basic') {
          // Generate variant-specific test code
          const { generateTestVariant } = await import('../../../services/testCaseGenerator.js');
          const variantTest = await generateTestVariant(
            test,
            variant as 'edge-case' | 'fuzz',
            finding
          );
          finalTestCode = variantTest.testCode;
          finalFileName = variantTest.testFileName;
        }

        // Write test file to workspace tests directory
        const testFilePath = path.join(testsPath, finalFileName);
        await fs.writeFile(testFilePath, finalTestCode, 'utf-8');

        generatedTests.push({
          ...test,
          testCode: finalTestCode,
          testFileName: finalFileName,
        });

        log.info('Generated test case', {
          findingId: finding.findingId,
          testFile: finalFileName,
          type: test.testType,
          variant: variant !== 'basic' ? variant : undefined,
        });
      } catch (error: any) {
        log.error('Failed to generate test for finding', {
          findingId: finding.findingId,
          variant,
          error: error.message,
        });

        errors.push({
          findingId: finding.findingId,
          error: `${variant}: ${error.message}`,
        });
      }
    }
  }

  await context.onProgress?.(95, 'Validating test coverage...');

  // Validate test coverage
  const { validateTestCoverage, generateCoverageReport } = await import('../../../services/testCoverageValidator.js');

  const coverageReport = validateTestCoverage(testableFindings, generatedTests);

  log.info('Test generation complete', {
    generated: generatedTests.length,
    failed: errors.length,
    coverage: `${coverageReport.testCoverage.toFixed(1)}%`,
    coverageGaps: coverageReport.coverageGaps.length,
    testsPath,
  });

  // Generate coverage report markdown
  const coverageMarkdown = generateCoverageReport(coverageReport);

  // Save coverage report to .uatu folder
  const coverageReportPath = path.join(testsPath, '..', '.uatu', 'test-coverage-report.md');
  await fs.ensureDir(path.dirname(coverageReportPath));
  await fs.writeFile(coverageReportPath, coverageMarkdown, 'utf-8');

  log.info('Saved test coverage report', { path: coverageReportPath });

  return {
    success: true,
    output: {
      testsGenerated: generatedTests.length,
      testsFailed: errors.length,
      testsPath,
      framework,
      testCoverage: coverageReport.testCoverage,
      coverageGaps: coverageReport.coverageGaps.length,
      errors: errors.length > 0 ? errors : undefined,
    },
    data: {
      generatedTests,
      testCoverageReport: coverageReport,
      errors,
    },
    findings: [],
  };
};

// ============================================================================
// Publish to GitHub Step
// ============================================================================

/**
 * Publish audit results to audited_{branch} branch
 * Includes findings, test cases, and reports
 */
const publishToGitHub: TestingExecutor = async (step, config, context) => {
  const { job } = context;
  const jobId = job.id;

  log.info('Publishing audit results to GitHub', { jobId });

  await context.onProgress?.(10, 'Preparing audit report...');

  try {
    // Get job to check workspace info
    const db = getDb();
    const [jobRecord] = await db
      .select()
      .from(auditJobs)
      .where(eq(auditJobs.id, jobId))
      .limit(1);

    if (!jobRecord || !jobRecord.metadata) {
      return {
        success: false,
        error: 'Job metadata not found',
        findings: [],
      };
    }

    const workspace = (jobRecord.metadata as any).workspace;
    if (!workspace) {
      return {
        success: false,
        error: 'Workspace info not found',
        findings: [],
      };
    }

    await context.onProgress?.(30, 'Publishing to GitHub...');

    // Publish audit results (includes tests if they exist)
    const result = await publishAuditResults(jobId, {
      includeTests: true,
      testsPath: workspace.testsPath,
      incrementalUpdate: true,
    });

    await context.onProgress?.(90, 'Published successfully');

    log.info('Published audit results to GitHub', {
      jobId,
      branch: result.branchName,
      commit: result.commitHash,
      url: result.repositoryUrl,
    });

    return {
      success: true,
      output: {
        branchName: result.branchName,
        commitHash: result.commitHash,
        repositoryUrl: result.repositoryUrl,
      },
      findings: [],
    };
  } catch (error: any) {
    log.error('Failed to publish to GitHub', {
      jobId,
      error: error.message,
    });

    return {
      success: false,
      error: `GitHub publish failed: ${error.message}`,
      findings: [],
    };
  }
};

// ============================================================================
// Validate Audit Completion Step (Deep Mode Monitoring)
// ============================================================================

/**
 * Validate that all SOP steps, test generation, and execution completed successfully
 * Uses Claude to analyze test failures and determine if they're real vulnerabilities
 * or system/package issues
 */
const validateAuditCompletion: TestingExecutor = async (step, config, context) => {
  const { projectPath, job } = context;
  const jobId = job.id;

  log.info('🔍 DEEP MODE: Validating audit completion and test results', { jobId });

  await context.onProgress?.(5, 'Collecting SOP execution data...');

  const db = getDb();
  const [jobRecord] = await db
    .select()
    .from(auditJobs)
    .where(eq(auditJobs.id, jobId))
    .limit(1);

  if (!jobRecord) {
    return {
      success: false,
      error: 'Job record not found',
      findings: [],
    };
  }

  const metadata = (jobRecord.metadata || {}) as any;
  const workspace = metadata.workspace;

  await context.onProgress?.(10, 'Analyzing test execution results...');

  // Get test generation results from context data
  const testsGenerated = context.data?.generatedTests || [];
  const testCoverageReport = context.data?.testCoverageReport;

  // Get test execution results
  const { auditResults } = await import('../../../db/schema.js');
  const [results] = await db
    .select()
    .from(auditResults)
    .where(eq(auditResults.jobId, jobId));

  if (!results) {
    return {
      success: false,
      error: 'Audit results not found',
      findings: [],
    };
  }

  const findings = (results.findings || []) as any[];
  const resultsMetadata = (results.metadata || {}) as any;
  const testResults = resultsMetadata.testResults || {};

  await context.onProgress?.(30, 'Analyzing with Claude AI...');

  // Build comprehensive validation prompt
  const validationPrompt = buildValidationPrompt({
    jobId,
    auditDepth: job.auditDepth || 'standard',
    testsGenerated: testsGenerated.length,
    testCoverageReport,
    testResults,
    findingsCount: findings.length,
    workspace,
    metadata: jobRecord.metadata,
  });

  log.info('Calling Claude for deep validation analysis', {
    testsGenerated: testsGenerated.length,
    findingsCount: findings.length,
  });

  // Call Claude to analyze the entire audit
  const { executeStreamingClaude } = await import('../../../services/ai/simpleClaudeExecutor.js');

  let validationReport: any;
  try {
    const result = await executeStreamingClaude(validationPrompt, {
      timeout: 300000, // 5 minutes for validation
      model: 'claude-opus-4-5-20251101',
    });

    const output = result.output || '';

    // Parse JSON response
    const jsonMatch = output.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('Could not parse validation report JSON');
    }

    validationReport = JSON.parse(jsonMatch[0]);

    log.info('✅ Validation analysis complete', {
      status: validationReport.overallStatus,
      issues: validationReport.issues?.length || 0,
    });
  } catch (error: any) {
    log.error('Failed to get validation analysis from Claude', { error: error.message });

    // Return a default validation report
    validationReport = {
      overallStatus: 'warning',
      message: 'Validation analysis failed, manual review recommended',
      issues: [{
        type: 'analysis_error',
        severity: 'medium',
        description: `Automated validation failed: ${error.message}`,
      }],
    };
  }

  await context.onProgress?.(80, 'Generating validation report...');

  // Save validation report to metadata
  const validationData = {
    timestamp: new Date().toISOString(),
    auditDepth: job.auditDepth,
    testsGenerated: testsGenerated.length,
    testResults: {
      total: testResults.total || 0,
      passed: testResults.passed || 0,
      failed: testResults.failed || 0,
    },
    validationReport,
  };

  // Update job metadata with validation results
  await db
    .update(auditJobs)
    .set({
      metadata: {
        ...metadata,
        validationReport: validationData,
      } as any,
    })
    .where(eq(auditJobs.id, jobId));

  log.info('Saved validation report to job metadata', {
    status: validationReport.overallStatus,
    issuesFound: validationReport.issues?.length || 0,
  });

  await context.onProgress?.(100, 'Validation complete');

  return {
    success: true,
    output: {
      status: validationReport.overallStatus,
      issues: validationReport.issues?.length || 0,
      testsValidated: testsGenerated.length,
      message: validationReport.message,
    },
    data: {
      validationReport: validationData,
    },
    findings: [],
  };
};

/**
 * Build validation prompt for Claude
 */
function buildValidationPrompt(data: {
  jobId: string;
  auditDepth: string;
  testsGenerated: number;
  testCoverageReport: any;
  testResults: any;
  findingsCount: number;
  workspace: any;
  metadata: any;
}): string {
  return `You are a security audit validator analyzing the completion status of a smart contract audit.

# Audit Context
- Audit Depth: ${data.auditDepth.toUpperCase()}
- Findings Identified: ${data.findingsCount}
- Tests Generated: ${data.testsGenerated}
- Test Coverage: ${data.testCoverageReport?.testCoverage?.toFixed(1) || 'N/A'}%

# Test Execution Results
${JSON.stringify(data.testResults, null, 2)}

# Test Coverage Report
${data.testCoverageReport ? JSON.stringify(data.testCoverageReport, null, 2) : 'No coverage report available'}

# Your Task
Analyze the audit completion and test execution results. Determine:

1. **SOP Completion Status**: Were all required steps completed successfully?
2. **Test Generation Quality**: Are the generated tests adequate for the findings?
3. **Test Failure Analysis**: For any failed tests, determine if they indicate:
   - ✅ REAL VULNERABILITY: Test correctly demonstrates a security issue (EXPECTED)
   - ❌ SYSTEM ISSUE: Test failure due to package/dependency/configuration problems (UNEXPECTED)
   - ⚠️ TEST ERROR: Test code has bugs and needs fixing (UNEXPECTED)

4. **False Positive Detection**: Are there tests that passed when they should have failed?
5. **Coverage Gaps**: Critical findings without test coverage?
6. **Overall Audit Quality**: Is the audit complete and reliable?

# Response Format (JSON ONLY)
Return a JSON object with this structure:

{
  "overallStatus": "success" | "warning" | "error",
  "message": "Brief summary of validation results",
  "sopValidation": {
    "allStepsCompleted": true | false,
    "missingSteps": ["step-id-1", "step-id-2"],
    "failedSteps": ["step-id-3"]
  },
  "testValidation": {
    "testsGenerated": ${data.testsGenerated},
    "testsExecuted": number,
    "testsPassed": number,
    "testsFailed": number,
    "adequateCoverage": true | false
  },
  "testFailureAnalysis": [
    {
      "testName": "test_name",
      "failureType": "real_vulnerability" | "system_issue" | "test_error",
      "confidence": "high" | "medium" | "low",
      "explanation": "Why this failure occurred",
      "recommendation": "What to do about it"
    }
  ],
  "issues": [
    {
      "type": "test_error" | "coverage_gap" | "false_positive" | "system_issue",
      "severity": "critical" | "high" | "medium" | "low",
      "description": "Detailed issue description",
      "affectedTests": ["test1", "test2"],
      "recommendation": "How to fix this issue"
    }
  ],
  "coverageGaps": [
    {
      "findingId": "finding-id",
      "severity": "critical" | "high",
      "reason": "Why no test was generated"
    }
  ],
  "recommendations": [
    "Recommendation 1",
    "Recommendation 2"
  ]
}

# Important Guidelines
- If tests FAIL because they demonstrate a vulnerability, that's EXPECTED (mark as "real_vulnerability")
- If tests FAIL due to missing packages, compilation errors, or configuration issues, that's UNEXPECTED (mark as "system_issue")
- If tests PASS when there's a real vulnerability, that's a problem (report as "false_positive")
- Only report actual problems in the "issues" array
- Be specific about what needs fixing

Return ONLY the JSON object, no markdown, no explanations.`;
}

// ============================================================================
// Executor Registry
// ============================================================================

const TESTING_EXECUTORS: Record<string, TestingExecutor> = {
  'generate-tests': generateTests,
  'publish-to-github': publishToGitHub,
  'validate-audit-completion': validateAuditCompletion,
};
